/*
 * nbody_cuda_driver_runtime.cpp
 *
 * Windows/MinGW driver-API host build ONLY (never compiled on Linux).
 * Provides:
 *  - lazy driver init + primary-context setup (nbEnsureCudaCtx)
 *  - loading the embedded multi-arch fatbin and resolving every
 *    kernel's CUfunction handle by its extern "C" name
 *  - the sticky launch-error slot the compat header's
 *    cudaGetLastError() reads back
 *
 * The fatbin is produced on Linux by `nvcc -fatbin` from the very same
 * nbody_cuda.cu the Linux binary is built from, then embedded as a C
 * array with bin2c into nbody_cuda_fatbin.h (generated by
 * build_cuda_win.sh). Same device code as the Linux app, bit for bit.
 */

#ifdef NBODY_CUDA_DRIVER_API

#include "nbody_cuda_driver_compat.h"
#include <stdio.h>

/* generated by build_cuda_win.sh: const unsigned char nb_cuda_fatbin[] */
#include "nbody_cuda_fatbin.h"

/* Windows GPU-host log prefix: HIP module-API build vs CUDA driver-API. */
#if defined(NBODY_HIP_DRIVER_API)
#  define NB_WIN_TAG "[nbody_hip_win]"
#  define NB_WIN_API "hip"          /* the cu* calls below are macro-mapped to hip* */
#  define NB_WIN_IMAGE "code object"
#else
#  define NB_WIN_TAG "[nbody_cuda_win]"
#  define NB_WIN_API "cu"
#  define NB_WIN_IMAGE "fatbin"
#endif

/* Defined in nbody_cuda_host.c (compiled into this driver-API host too).
 * Returns the GPU ordinal BOINC assigned / --device requested. */
extern "C" int nbCUDAGetTargetDevice(void);

CUresult nb_last_launch_err = CUDA_SUCCESS;

#define NB_DEFINE_FN(k) CUfunction nbfn_##k = NULL;
NB_KERNEL_LIST(NB_DEFINE_FN)
#undef NB_DEFINE_FN

static CUdevice  g_dev = 0;
static CUcontext g_ctx = NULL;
static CUmodule  g_mod = NULL;
static int g_ctx_ok = -1;   /* -1 = not tried, 0 = ok, 1 = failed */

CUdevice nbCudaDevice(void) { return g_dev; }

int nbEnsureCudaCtx(void) {
    if (g_ctx_ok == 0) return 0;
    if (g_ctx_ok == 1) return -1;

#if defined(NBODY_HIP_DYNLOAD)
    /* resolve amdhip64 (LoadLibrary/dlopen) before the first HIP call */
    if (nbHipLoadRuntime()) { g_ctx_ok = 1; return -1; }
    {
        /* which HIP this driver ships: an old (HIP 5.x) runtime is the usual
         * reason a code object fails to load */
        int rtv = 0;
        if (hipRuntimeGetVersion(&rtv) == hipSuccess)
            fprintf(stderr, NB_WIN_TAG " HIP runtime version %d\n", rtv);
    }
#endif

    CUresult e = cuInit(0);
    if (e != CUDA_SUCCESS) {
        fprintf(stderr, NB_WIN_TAG " " NB_WIN_API "Init failed: %d\n", (int)e);
        g_ctx_ok = 1;
        return -1;
    }
    /* Honor the GPU BOINC assigned (gpu_device_num) / --device override
     * instead of always binding ordinal 0. */
    const int wantDev = nbCUDAGetTargetDevice();
    e = cuDeviceGet(&g_dev, wantDev);
    if (e != CUDA_SUCCESS) {
        fprintf(stderr, NB_WIN_TAG " could not select GPU device %d (err %d) — check --device / BOINC GPU assignment\n", wantDev, (int)e);
        g_ctx_ok = 1;
        return -1;
    }
    /* primary context: same context the runtime API would use, keeps
     * any future runtime-API interop possible */
    e = cuDevicePrimaryCtxRetain(&g_ctx, g_dev);
    if (e != CUDA_SUCCESS) {
        fprintf(stderr, NB_WIN_TAG " " NB_WIN_API "DevicePrimaryCtxRetain failed: %d\n", (int)e);
        g_ctx_ok = 1;
        return -1;
    }
    e = cuCtxSetCurrent(g_ctx);
    if (e != CUDA_SUCCESS) {
        fprintf(stderr, NB_WIN_TAG " " NB_WIN_API "CtxSetCurrent failed: %d\n", (int)e);
        g_ctx_ok = 1;
        return -1;
    }
    g_ctx_ok = 0;

    /* load the embedded fatbin + resolve kernel handles now, so every
     * nbfn_* is valid before the first NB_LAUNCH */
    if (nbCudaLoadModule()) {
        g_ctx_ok = 1;
        return -1;
    }
    return 0;
}

int nbCudaLoadModule(void) {
    if (g_mod) return 0;
    if (nbEnsureCudaCtx()) return -1;

    CUresult e = cuModuleLoadData(&g_mod, nb_cuda_fatbin);
    if (e != CUDA_SUCCESS) {
        const char* s = NULL;
        cuGetErrorString(e, &s);
        fprintf(stderr, NB_WIN_TAG " " NB_WIN_API "ModuleLoadData(" NB_WIN_IMAGE ") failed: %s (%d)\n",
                s ? s : "?", (int)e);
#if defined(NBODY_HIP_DRIVER_API)
        if ((int)e == 303)   /* hipErrorSharedObjectInitFailed */
            fprintf(stderr, NB_WIN_TAG " the HIP runtime rejected the embedded code object - "
                            "usually an AMD driver whose HIP runtime is too old for it\n");
#endif
        return -1;
    }

    int missing = 0;
#define NB_RESOLVE_FN(k) \
    if (cuModuleGetFunction(&nbfn_##k, g_mod, #k) != CUDA_SUCCESS) { \
        fprintf(stderr, NB_WIN_TAG " kernel not found in " NB_WIN_IMAGE ": %s\n", #k); \
        missing++; \
    }
    NB_KERNEL_LIST(NB_RESOLVE_FN)
#undef NB_RESOLVE_FN

    if (missing) {
        fprintf(stderr, NB_WIN_TAG " %d kernel(s) unresolved\n", missing);
        return -1;
    }
    return 0;
}

#endif /* NBODY_CUDA_DRIVER_API */
