#!/usr/bin/env python3
# Minimal bin2c: emit a C array from a binary file. Used to embed the HIP
# code object (and, if ever needed, any blob) into a header the driver-API
# host TU includes. Mirrors nvcc's bin2c --const output closely enough for
# nbody_cuda_driver_runtime.cpp (which just needs `const unsigned char <name>[]`).
import sys

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: bin2c.py <input-blob> <symbol-name>\n")
        return 1
    path, name = sys.argv[1], sys.argv[2]
    with open(path, "rb") as f:
        data = f.read()
    out = sys.stdout
    out.write("/* generated by tools/bin2c.py -- do not edit */\n")
    out.write("const unsigned char %s[] = {\n" % name)
    for i in range(0, len(data), 20):
        out.write(" " + ",".join(str(b) for b in data[i:i+20]) + ",\n")
    out.write("};\n")
    out.write("const unsigned long %s_len = %d;\n" % (name, len(data)))
    return 0

if __name__ == "__main__":
    sys.exit(main())
